image: carvicsforth/centos_carv:latest
#image: bob.ics.forth.gr:443/jvm_ci/spark-base
stages:
    - build
    - test

jvm_release_build:
  stage: build
  script:
    - cd allocator
    - ./build.sh docker
    - export LIBRARY_PATH=$(pwd)/lib/:$LIBRARY_PATH
    - export LD_LIBRARY_PATH=$(pwd)/lib/:$LD_LIBRARY_PATH                                                                                           
    - export PATH=$(pwd)/include/:$PATH
    - export C_INCLUDE_PATH=$(pwd)/include/:$C_INCLUDE_PATH                                                                                         
    - export CPLUS_INCLUDE_PATH=$(pwd)/include/:$CPLUS_INCLUDE_PATH
    - cd ../openjdk-8/openjdk8
    - bash ./configure --with-jobs=1 --disable-debug-symbols --with-extra-cflags='-O3' --with-extra-cxxflags='-O3'
    - make DISABLE_HOTSPOT_OS_VERSION_CHECK=ok

jvm_debug_build:
  stage: build
  script:
    - cd allocator
    - ./build.sh docker
    - export LIBRARY_PATH=$(pwd)/lib/:$LIBRARY_PATH
    - export LD_LIBRARY_PATH=$(pwd)/lib/:$LD_LIBRARY_PATH                                                                                           
    - export PATH=$(pwd)/include/:$PATH
    - export C_INCLUDE_PATH=$(pwd)/include/:$C_INCLUDE_PATH                                                                                         
    - export CPLUS_INCLUDE_PATH=$(pwd)/include/:$CPLUS_INCLUDE_PATH
    - cd ../openjdk-8/openjdk8
    - bash ./configure --with-debug-level=release --with-target-bits=64 --disable-zip-debug-info --with-jobs=32
    - make DISABLE_HOTSPOT_OS_VERSION_CHECK=ok

prepare_test:
  stage: test
  script:
    - echo 'Hello $GITLAB_USER_NAME, testing is under construction! Please be patient'
    - echo 'This is the value of LIBRARY_PATH $LIBRARY_PATH'